### ISSUE TITLE
Stage4 - acceptance tests

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/bitEncoderDecoderCollaboration#26]

**Comment by PawelDabrowski83** [comment]
I will leave this unmerged yet, because I would like to set a release for Stage3 on Wednesday, and this is part of Stage4.
I will add some more tests for this stage in another PR.

**Comment by tyczynoprzemyslaw** [comment]
Hey, Can You get me info what we should test? I would like to write it ;)
