### ISSUE TITLE
Stage3 - regarding correct input

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/bitEncoderDecoderCollaboration#48]
Our current specification states that String after stage2.send() is always corrupted, such as: "aaabbb" -> "ala_bb".

Do you think we need a test on Stage3 to check if input follow this pattern?

Consider this case on Stage3: with input="abcTTyTTo" we get output " TT". I would expect throwing an exception pointing out that something has gone wrong.

**Comment by tyczynoprzemyslaw** [comment]
I don't think so. In this particular case we are sure, send() will always get input from encode()

**Comment by PawelDabrowski83** [comment]
We check if input is correct on every stage, and this is good, because test should protect us from commiting an implementation with bugs.

I just think that Stage3 test, when checking input should verify whether pattern is correct. Valid input is triplet with one repetition, such as "aab" -> "a". If there is no repetition, it means that String cannot be decoded. This is why I think that we should throw an Exception.

**Comment by tyczynoprzemyslaw** [comment]
Okey, now it makes sens for me.

**Comment by PawelDabrowski83** [comment]
Issue will be resolved on another issue - tests of custom Exception.
